// Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Ring
{
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for Dings.
    /// </summary>
    public static partial class DingsExtensions
    {
            /// <summary>
            /// Dings
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='authToken'>
            /// </param>
            public static void Get(this IDings operations, string authToken = default(string))
            {
                operations.GetAsync(authToken).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Dings
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='authToken'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task GetAsync(this IDings operations, string authToken = default(string), CancellationToken cancellationToken = default(CancellationToken))
            {
                (await operations.GetWithHttpMessagesAsync(authToken, null, cancellationToken).ConfigureAwait(false)).Dispose();
            }

            /// <summary>
            /// Last Recording
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='responseBodyPath'>
            /// </param>
            /// <param name='authToken'>
            /// </param>
            public static void GetLastRecording(this IDings operations, string responseBodyPath, string authToken = default(string))
            {
                operations.GetLastRecordingAsync(responseBodyPath, authToken).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Last Recording
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='responseBodyPath'>
            /// </param>
            /// <param name='authToken'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task GetLastRecordingAsync(this IDings operations, string responseBodyPath, string authToken = default(string), CancellationToken cancellationToken = default(CancellationToken))
            {
                (await operations.GetLastRecordingWithHttpMessagesAsync(responseBodyPath, authToken, null, cancellationToken).ConfigureAwait(false)).Dispose();
            }

    }
}
