// Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Ring
{
    using Models;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for History.
    /// </summary>
    public static partial class HistoryExtensions
    {
            /// <summary>
            /// History
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='authToken'>
            /// </param>
            public static void Get(this IHistory operations, string authToken = default(string))
            {
                operations.GetAsync(authToken).GetAwaiter().GetResult();
            }

            /// <summary>
            /// History
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='authToken'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task GetAsync(this IHistory operations, string authToken = default(string), CancellationToken cancellationToken = default(CancellationToken))
            {
                (await operations.GetWithHttpMessagesAsync(authToken, null, cancellationToken).ConfigureAwait(false)).Dispose();
            }

    }
}
