// Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Ring.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Session
    {
        /// <summary>
        /// Initializes a new instance of the Session class.
        /// </summary>
        public Session()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Session class.
        /// </summary>
        public Session(SessionProfile profile = default(SessionProfile))
        {
            Profile = profile;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "profile")]
        public SessionProfile Profile { get; set; }

    }
}
