// Code generated by Microsoft (R) AutoRest Code Generator 1.0.1.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Ring.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class SessionProfile
    {
        /// <summary>
        /// Initializes a new instance of the SessionProfile class.
        /// </summary>
        public SessionProfile()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SessionProfile class.
        /// </summary>
        public SessionProfile(string id = default(string), string email = default(string), string firstName = default(string), string lastName = default(string), string phoneNumber = default(string), string authenticationToken = default(string), object features = default(object))
        {
            Id = id;
            Email = email;
            FirstName = firstName;
            LastName = lastName;
            PhoneNumber = phoneNumber;
            AuthenticationToken = authenticationToken;
            Features = features;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "email")]
        public string Email { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "first_name")]
        public string FirstName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "last_name")]
        public string LastName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "phone_number")]
        public string PhoneNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "authentication_token")]
        public string AuthenticationToken { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "features")]
        public object Features { get; set; }

    }
}
